export const SectionTheme = {
  Section: {
    type: {
      header: {
        display: "grid",
        grid: "",
        justifyContent: "",
        justifyItems: "",
        alignContent: "",
        alignItems: "",
      },
      search: {
        display: "",
        grid: "",
        justifyContent: "",
        justifyItems: "",
        alignContent: "",
        alignItems: "",
      },
      button: {
        display: "",
        grid: "",
        justifyContent: "",
        justifyItems: "",
        alignContent: "",
        alignItems: "",
      },
      buttons: {
        display: "",
        grid: "",
        justifyContent: "",
        justifyItems: "",
        alignContent: "",
        alignItems: "",
      },
      imageText: {
        display: "",
        grid: "",
        justifyContent: "",
        justifyItems: "",
        alignContent: "",
        alignItems: "",
      },
      popup: {
        display: "",
        grid: "",
        justifyContent: "",
        justifyItems: "",
        alignContent: "",
        alignItems: "",
      },
      modal: {
        display: "",
        grid: "",
        justifyContent: "",
        justifyItems: "",
        alignContent: "",
        alignItems: "",
      },
      groupNumber: {
        display: "",
        grid: "",
        justifyContent: "",
        justifyItems: "",
        alignContent: "",
        alignItems: "",
      },
    },
  },
};
