name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t word-book-frontend-test:tt .

  build:
    name: Build
    runs-on: self-hosted
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Stop old container
        run: docker stop word-book-frontend-prod

      - name: Clear all docker instance
        run: docker system prune -af --volumes

      - name: Build the Docker image
        run: docker build -f Dockerfile.prod -t word-book-frontend-prod:pd .

      - name: Spin up the container
        run: docker run -d -p 8080:80 --name word-book-frontend-prod word-book-frontend-prod:pd